# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JustCircleCIRxSwift' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RxSwift'
  pod 'RxCocoa'

  # Pods for JustCircleCIRxSwift

  target 'JustCircleCIRxSwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JustCircleCIRxSwiftUITests' do
    # Pods for testing
  end

end
